#!/bin/bash
set -e
source "$HOME/lfs-build/config.sh"


run_chroot() {
    sudo chroot "$LFS" /usr/bin/env -i \
        HOME=/root \
        TERM="${TERM:-xterm}" \
        PS1='(lfs chroot) \u:\w\$ ' \
        PATH=/usr/bin:/usr/sbin \
        MAKEFLAGS="-j$(nproc)" \
        TESTSUITEFLAGS="-j$(nproc)" \
        /bin/bash --login -c "$1"
}

echo "Iniciando Zlib temporário..."

run_chroot '
set -e
cd /sources
rm -rf zlib-1.3.2
tar -xf zlib-1.3.2.tar.gz
cd zlib-1.3.2

./configure --prefix=/usr
make
make install
rm -fv /usr/lib/libz.a

cd /sources
rm -rf zlib-1.3.2
'

echo "Zlib temporário concluído com sucesso."

